### ISSUE TITLE
SoignerPokemon

### ISSUE THREAD

**Issue by caliendojulien** [LAZ-R/TpPokemon#1]
https://github.com/LAZ-R/TpPokemon/blob/0fa3f31ba6a1dbe7dcd50ec180c2f394cc4c1095/src/fr/eni/quelPokemon/bo/CentrePkmn.java#L5

Si la méthode permet de soigner des Pokémons, je préfèrerais qu'elle prenne en paramètre un tableau de Pokémons. Ce serait plus logique.

**Comment by LAZ-R** [comment]
Je ne suis pas d'accord avec toi sur le principe en fait, cette méthode est contenue dans la classe "Centre Pokémon", dans le centre pokémon c'est le dresseur qui interagit avec le staff, et cette méthode permets justement de soigner TOUS les pokémons de CE dresseur... Je comprends ce que tu veux dire, mais à la limite je peux changer le nom de la méthode ?

**Comment by caliendojulien** [comment]
Ok, ca me va.
